baseURL: https://weslack.team
title: weslack
theme: hugo-notepadium
copyright: ©2020 weslack
languageCode: en
defaultContentLanguage: en
hasCJKLanguage: true
enableRobotsTXT: true
markup:
  highlight:
    codeFences: true
    noClasses: false
  goldmark:
    renderer:
      unsafe: false
params:
  style: auto
  dateFormat: 'Jan 02, 2006'
  readingTime: false
  logo: logo.png
  slogan: DEFCON 28 CTF Fun
  assets:
    css:
      - css/fonts.css
  comments:
    enable: false
  share:
    enable: false
    addThisId: ''
    inlineToolId: ''
  math:
    enable: false
    use: katex
  syntax:
    use: none
    theme: github
    darkTheme: dracula
  profile:
    enable: false
    avatar: >-
      https://d33wubrfki0l68.cloudfront.net/ddf49425628d8aec7523db143916b34ae1641e11/b97e8/images/gopher-side_color.svg
    name: weslack
    bio: >-
      Hugo is one of the most popular open-source static site generators. With
      its amazing speed and flexibility, Hugo makes building websites fun again.
    github: weslack
  nav:
    showCategories: true
    showTags: true
    custom:
      - title: About
        url: /about/
      - title: GitHub
        url: https://github.com/weslack
