baseURL: https://weslack.team
title: weslack
theme: hugo-notepadium
copyright: All content is free, unencumbered, and released into the public domain. Do with it what you want. <a href="/LICENSE.txt">Unlicense</a>
languageCode: en
defaultContentLanguage: en
hasCJKLanguage: true
enableRobotsTXT: true
enableGitInfo: true
markup:
  highlight:
    codeFences: true
    noClasses: false
  goldmark:
    renderer:
      unsafe: false
frontmatter:
  date:
    - "date"
    - ":git"
    - ":fileModTime"
    - "publishDate"
  lastmod:
    - ":git"
    - ":fileModTime"
    - "lastmod"
  publishDate:
    - "publishDate"
    - "date"
  expiryDate:
    - "expiryDate"
params:
  style: auto
  dateFormat: Mon, 02 Jan 2006 15:04:05
  readingTime: false
  logo: logo.png
  slogan: DEFCON 28 CTF Fun
  assets:
    css:
      - css/fonts.css
  comments:
    enable: false
  share:
    enable: false
    addThisId: ''
    inlineToolId: ''
  math:
    enable: false
    use: katex
  syntax:
    use: none
    theme: github
    darkTheme: dracula
  nav:
    showCategories: true
    showTags: true
    custom:
      - title: About
        url: /about/
      - title: GitHub
        url: https://github.com/weslack
